EL_ShopPricesConfig {
 m_iDefaultBuyPrice 50
 m_iDefaultSellPrice 25
 m_aPriceRules {
  EL_ShopPriceRule "{4BD2E0331EA7CABD}" {
   m_sFind "Prefabs/Items/Currencies/"
   m_bHidden 1
  }
  EL_ShopPriceRule "{0B3E30AD3EB96CD5}" {
   m_sFind "Prefabs/Items/Roleplay/"
   m_bHidden 1
  }
  EL_ShopPriceRule "{278731F73235269F}" {
   m_sFind "Prefabs/Items/HouseKeyItem"
   m_bHidden 1
  }
  EL_ShopPriceRule "{42770C0667B38CE2}" {
   m_sFind "Prefabs/Items/Seeds/"
   m_iBuyPrice 4
   m_iSellPrice 2
  }
  EL_ShopPriceRule "{4A242A99E0ACD0AC}" {
   m_sFind "Prefabs/Items/Food/"
   m_iBuyPrice 8
   m_iSellPrice 4
  }
  EL_ShopPriceRule "{256ABB27ED43C8D5}" {
   m_sFind "Prefabs/Items/Drinks/"
   m_iBuyPrice 6
   m_iSellPrice 3
  }
  EL_ShopPriceRule "{F80E3819F33BF747}" {
   m_sFind "Prefabs/Items/Resources/"
   m_iBuyPrice 12
   m_iSellPrice 6
  }
  EL_ShopPriceRule "{AB8B3ECDA7603995}" {
   m_sFind "Prefabs/Resources/WoodCutting/"
   m_iBuyPrice 10
   m_iSellPrice 5
  }
  EL_ShopPriceRule "{6FC124D7FAF7002D}" {
   m_sFind "Prefabs/Resources/Mining/"
   m_iBuyPrice 25
   m_iSellPrice 12
  }
  EL_ShopPriceRule "{D549500CAA778001}" {
   m_sFind "Prefabs/Tools/"
   m_iBuyPrice 100
   m_iSellPrice 50
  }
  EL_ShopPriceRule "{4F86ED7939B52792}" {
   m_sFind "Prefabs/Weapons/"
   m_iBuyPrice 800
   m_iSellPrice 400
  }
  EL_ShopPriceRule "{67068DFD0A1AA106}" {
   m_sFind "Handgun_M9"
   m_iBuyPrice 500
   m_iSellPrice 250
  }
  EL_ShopPriceRule "{63681FB2C2EB2142}" {
   m_sFind "Prefabs/Resources/Mining/GoldNugget.et"
   m_iBuyPrice 60
   m_iSellPrice 35
  }
  EL_ShopPriceRule "{A0EB71249E56289D}" {
   m_sFind "Prefabs/Resources/Mining/IronBar.et"
   m_iBuyPrice 80
   m_iSellPrice 45
  }
  EL_ShopPriceRule "{E83D4FE991F093B1}" {
   m_sFind "Prefabs/Resources/Mining/CopperBar.et"
   m_iBuyPrice 60
   m_iSellPrice 35
  }
  EL_ShopPriceRule "{4D30DC2DC341D2AA}" {
   m_sFind "Prefabs/Resources/Mining/GoldBar.et"
   m_iBuyPrice 250
   m_iSellPrice 150
  }
  EL_ShopPriceRule "{0B18BE79F7E60CC9}" {
   m_sFind "Prefabs/Tools/Axe"
   m_iBuyPrice 120
   m_iSellPrice 60
  }
  EL_ShopPriceRule "{B525C6579582C18E}" {
   m_sFind "Prefabs/Tools/Pickaxe"
   m_iBuyPrice 150
   m_iSellPrice 75
  }
 }
 m_aExtraItemPrefabs {
  "{5439738849229352}Prefabs/Items/Currencies/MoneyStack.et"
  "{C9D661E5B0714711}Prefabs/Items/Food/Apple.et"
  "{C3E35D690317B5BE}Prefabs/Items/Food/Plum.et"
  "{0815D91FDF997A0A}Prefabs/Items/Food/Tomato.et"
  "{9FEBBF75B1D525EE}Prefabs/Items/Food/Cabbage.et"
  "{73CF2BF72525F5D5}Prefabs/Items/Food/RowanBerries.et"
  "{A231A5F8D479B5DC}Prefabs/Items/Drinks/WaterBottle.et"
  "{1DBD99E6347DE1AD}Prefabs/Items/Drinks/AppleJuice.et"
  "{97F71E1D9830AE26}Prefabs/Items/Seeds/SeedTomato.et"
  "{D58674633332DC86}Prefabs/Items/Resources/CementBag.et"
  "{344090890C63F4CA}Prefabs/Items/Resources/GravelBag.et"
  "{ADFEF306D1C22E5F}Prefabs/Items/Resources/Sandbag.et"
  "{0D5DA590E223A195}Prefabs/Items/Resources/Brick.et"
  "{6853E2E2AE878611}Prefabs/Resources/Mining/IronNugget.et"
  "{8F81BD0BF343CF49}Prefabs/Resources/Mining/GoldNugget.et"
  "{1881C4F2BD43E3E1}Prefabs/Resources/Mining/CopperNugget.et"
  "{BCD1E8CD7F975074}Prefabs/Resources/Mining/IronBar.et"
  "{ACC9A10F0F20F5C4}Prefabs/Resources/Mining/GoldBar.et"
  "{577A665F1662E7AD}Prefabs/Resources/Mining/CopperBar.et"
  "{45D1B36F99DD2FC3}Prefabs/Resources/WoodCutting/WoodPlank.et"
  "{32F5A906D8A573BC}Prefabs/Resources/WoodCutting/WoodLog_01_Small.et"
  "{6697C9B8CEB5234C}Prefabs/Resources/WoodCutting/WoodKindling.et"
  "{9CAC68BA551417A4}Prefabs/Tools/Axe/Axe.et"
  "{23341E2840F5ACB4}Prefabs/Tools/Pickaxe.et"
  "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
 }
}