PersistenceSystemConfig : "{3A03B52D11F7C36A}Configs/Systems/Persistence/Common.conf" {
 Collections {
  PersistenceCollection "{82DF002A753D442D}" {
   Name "LifeFramework"
   Storage "{62488048AF9D8A55}"
  }
 }
 Bundles {
  PersistenceBundle WorldState {
   Collections +{
    "{82DF002A753D442D}"
   }
  }
 }
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Setup {
     Configurations {
      EntityPersistenceConfig "{65ACD95F40F6C669}" {
       EntitySerializer SCR_GameModeSerializer "{691481C816B7FF22}" {
       }
       ComponentSerializers {
        SCR_NightModeGameModeComponentSerializer "{65DA86351E4300EF}" {
        }
        SCR_AdditionalGameModeSettingsComponentSerializer "{65DA86355D98D1C1}" {
        }
        SCR_PerceivedFactionManagerComponentSerializer "{65DA86318FC55714}" {
        }
        SCR_ArsenalManagerComponentSerializer "{65DAC3D5406631C6}" {
        }
        SCR_GameModeHealthSettingsSerializer "{65DAC3D8D904180B}" {
        }
        SCR_NotificationSenderComponentSerializer "{65DAC3DE5D67A74E}" {
        }
        SCR_PlayerSpawnPointManagerComponentSerializer "{65DAC3C35F0C362B}" {
        }
        SCR_RespawnSystemComponentSerializer "{65DC86C8BC352C65}" {
        }
        EL_PersistenceComponentSerializer "{5CFEF162615280AC}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{64ECE6462993EA13}" {
       SelfSpawn 1
      }
     }
    }
    PersistenceConfigGroup LifeFramework {
     Configurations {
      EntityPersistenceConfig "{7A15478CC456182F}" {
       Rule ComponentClassPersistenceConfigRule "{81257B50BE18EAC3}" {
        ComponentClass "EL_QuantityComponent"
       }
       Collection "{82DF002A753D442D}"
       Priority 35000
       SelfSpawn 1
       ParentHandling "Ignore always"
       EntitySerializer GenericEntitySerializer "{6B0E7A237C91F5BE}" {
       }
       ComponentSerializers {
        EL_QuantityComponentSerializer "{0789DFA67DE9F9F8}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup Structures {
     Configurations {
      EntityPersistenceConfig "{6968896F29096D64}" {
       Collection "{65B4DD18C4F30AC9}"
      }
      EntityPersistenceConfig "{65B682661F79DDBE}" {
       Collection "{65B4DD18C4F30AC9}"
      }
     }
    }
   }
  }
 }
}