MenuManager {
   MenuPresets {
      MenuPreset EL_SplitQuantityDialog {
         Layout "{CBD13209101AACEE}UI/Layouts/Menus/Inventory/SplitQuantityDialog.layout"
         Class "EL_SplitQuantityDialog"
      }
      MenuPreset ATM {
         Layout "{8012E7D806E87F1A}UI/Layouts/EL_ATMMenu.layout"
         Class "EL_ATMMenu"
      }
      MenuPreset SurvivalHUD {
         Layout "{64B1F5DD29214016}UI/Layouts/EL_SurvivalHUD.layout"
         Class "EL_SurvivalHUD"
      }
      MenuPreset Shop {
         Layout "{CE3AB8A674B242C5}UI/Layouts/ShopMenu.layout"
         Class "EL_ShopMenu"
      }
      MenuPreset PoliceMenu {
         Layout "{41C6F92AE5EA775C}UI/Layouts/PoliceMenu.layout"
         Class "EL_PoliceMenu"
      }
      MenuPreset DebugMenu {
         Layout "{FD1A363529A0954F}UI/Layouts/DebugMenu.layout"
         Class "EL_DebugMenu"
      }
   }
}