MenuManager {
 MenuPresets {
  MenuPreset EL_SplitQuantityDialog {
   Layout "{CBD13209101AACEE}UI/Layouts/Menus/Inventory/SplitQuantityDialog.layout"
   Class "EL_SplitQuantityDialog"
  }
  MenuPreset CharacterCreation {
   Layout "UI/Layouts/EL_CharacterCreationMenu.layout"
   Class "EL_CharacterCreationMenu"
  }
  MenuPreset ATM {
   Layout "UI/Layouts/EL_ATMMenu.layout"
   Class "EL_ATMMenu"
  }
  MenuPreset SurvivalHUD {
   Layout "UI/Layouts/EL_SurvivalHUD.layout"
   Class "EL_SurvivalHUD"
  }
MenuPreset FactionSelection {
     Layout "UI/Layouts/FactionSelectionMenu.layout"
     Class "EL_FactionSelectionMenu"
    }
    MenuPreset CharacterCreationMenu {
     Layout "{D9C065A9AD23B91B}UI/Layouts/EL_CharacterCreationMenu.layout"
     Class "EL_CharacterCreationMenu"
    }
    MenuPreset Shop {
    Layout "UI/Layouts/ShopMenu.layout"
    Class "EL_ShopMenu"
   }
   MenuPreset PoliceMenu {
    Layout "UI/Layouts/PoliceMenu.layout"
    Class "EL_PoliceMenu"
   }
 }
}