MenuManager {
 MenuPresets {
  MenuPreset EL_SplitQuantityDialog {
   Layout "{CBD13209101AACEE}UI/Layouts/Menus/Inventory/SplitQuantityDialog.layout"
   Class "EL_SplitQuantityDialog"
  }
  MenuPreset CharacterCreation {
   Layout "UI/Layouts/EL_CharacterCreationMenu.layout"
   Class "EL_CharacterCreationMenu"
  }
  MenuPreset ATM {
   Layout "UI/Layouts/EL_ATMMenu.layout"
   Class "EL_ATMMenu"
  }
  MenuPreset SurvivalHUD {
   Layout "UI/Layouts/EL_SurvivalHUD.layout"
   Class "EL_SurvivalHUD"
  }
  MenuPreset LF_GroupMenu {
   Layout "UI/Layouts/GroupMenu.layout"
   Class "EL_GroupMenu"
  }
  MenuPreset LF_GroupInviteDialog {
   Layout "UI/Layouts/GroupInviteDialog.layout"
   Class "EL_GroupInviteDialog"
  }
  MenuPreset FurnitureShopMenu {
   Layout "{21A17D11E5D2CA0B}UI/Layouts/FurnitureShopMenu.layout"
   Class "EL_FurnitureShopMenu"
  }
  MenuPreset PropertyMenu {
   Layout "{6EDC6B3C72A14911}UI/Layouts/PropertyMenu.layout"
   Class "EL_PropertyMenu"
  }
   MenuPreset FactionSelection {
    Layout "UI/Layouts/FactionSelectionMenu.layout"
    Class "EL_FactionSelectionMenu"
   }
   MenuPreset CharacterCreationMenu {
    Layout "{D9C065A9AD23B91B}UI/Layouts/EL_CharacterCreationMenu.layout"
    Class "EL_CharacterCreationMenu"
   }
   MenuPreset EL_Garage {
    Layout "UI/Layouts/GarageMenu.layout"
    Class "EL_GarageMenu"
   }
   MenuPreset Shop {
    Layout "UI/Layouts/ShopMenu.layout"
    Class "EL_ShopMenu"
   }
   MenuPreset PoliceMenu {
    Layout "UI/Layouts/PoliceMenu.layout"
    Class "EL_PoliceMenu"
   }
 }
}