// GENERATED FILE - do not edit by hand.
// Regenerated by 'tools\cli regen-tests' and checked by 'tools\cli validate'.
// Every test class declares its tier with a '// tier:' comment above its declaration;
// this registry is derived from those files in deterministic order.
class EL_TestRegistrations
{
	static void RegisterAll(EL_TestManager manager)
	{
		manager.Register(new EL_Test_WorldLoaded(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_MoneyStackPrefab(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_MathStringSanity(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ContextSelfTest(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountWantedClamp(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountCharacterRoster(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountSaveRoundtrip(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountManagerCache(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountActiveIndex(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_AccountCachePolicy(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_BankAccountMath(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_BankSaveRoundtrip(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ATMManagerRegistry(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ChatChannels(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_Data(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_FactionSpawn(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_FormatAbbreviate(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_UtilsMinMax(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_IDCard(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_LicensePlateFormat(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_LicensePlateParenting(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_LoggingChain(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_MoneyCash(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_MoneyRework(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_PoliceFineMath(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_PoliceOnDutyOfficer(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_Prefabs(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_QuantityStack(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_FruitCatcherRewardClamp(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ShopQuantityGate(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ShopTotalPrice(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ATMAmountGuard(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_Siren(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_SirenMode(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_Survival(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_SurvivalSaveData(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_TraderItemConfig(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_ProcessingRecipeConfig(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_VehicleLock(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_VehicleLockIdMatch(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_WhitelistChatResources(), EL_TestTier.WORLD);
		manager.Register(new EL_Test_WhitelistLogic(), EL_TestTier.LOGIC);
		manager.Register(new EL_Test_WhitelistCommandParse(), EL_TestTier.LOGIC);
	}
}

