# tools/validation/gen-test-registry.ps1 - auto-generate the EL_Test registry.
#
# The test registry used to be a hand-edited list inside EL_TestManager.c, which
# made it a single-writer file that parallel agents could not touch safely. This
# script derives the registry from the test files themselves, so the registry is
# machine-maintained and any agent that adds a test file just regenerates it.
#
# Contract (mirrored by validate-tests.ps1):
#   1. Every class matching `class EL_Test_\w+ : EL_Test` in the top level of
#      Scripts/Game/Tests/ must declare a `// tier: LOGIC|WORLD|PERSISTENCE`
#      comment above its declaration. The tier drives which suites run it.
#   2. The generated file EL_TestRegistrations.generated.c registers every such
#      class through EL_TestManager.Register, in deterministic file order.
#   3. The generated file is never edited by hand; regenerate it instead.
#
# Modes:
#   -Write   regenerate EL_TestRegistrations.generated.c in place
#   -Check   regenerate to a string and compare with disk (exit 1 on drift)
#
# Exit codes: 0 = contract holds / written, 1 = violations or drift.

param(
  [switch]$Write,
  [switch]$Check
)

$ErrorActionPreference = "Stop"

$root = git rev-parse --show-toplevel
if (-not $root) { Write-Host "ERROR not a git work tree"; exit 1 }

$testsDir = Join-Path $root "addons\LifeFramework\Scripts\Game\Tests"
$generatedPath = Join-Path $testsDir "EL_TestRegistrations.generated.c"
$generatedName = "EL_TestRegistrations.generated.c"

$entries = @()
$violations = @()

Get-ChildItem $testsDir -Filter "*.c" | Where-Object { $_.Name -ne $generatedName } | Sort-Object Name | ForEach-Object {
  $file = $_
  $text = Get-Content $file.FullName -Raw

  $matches = [regex]::Matches($text, 'class\s+(EL_Test_\w+)\s*:\s*EL_Test')
  foreach ($m in $matches) {
    $cls = $m.Groups[1].Value

    $segment = $text.Substring(0, $m.Index)
    $tierMatch = [regex]::Matches($segment, '//\s*tier:\s*(LOGIC|WORLD|PERSISTENCE)')
    if ($tierMatch.Count -eq 0) {
      $violations += "$($file.Name): class $cls has no '// tier:' comment above its declaration"
      continue
    }

    $tier = $tierMatch[$tierMatch.Count - 1].Groups[1].Value
    $entries += [PSCustomObject]@{ File = $file.Name; Class = $cls; Tier = $tier }
  }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// GENERATED FILE - do not edit by hand.")
[void]$sb.AppendLine("// Regenerated by 'tools\cli regen-tests' and checked by 'tools\cli validate'.")
[void]$sb.AppendLine("// Every test class declares its tier with a '// tier:' comment above its declaration;")
[void]$sb.AppendLine("// this registry is derived from those files in deterministic order.")
[void]$sb.AppendLine("class EL_TestRegistrations")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("`tstatic void RegisterAll(EL_TestManager manager)")
[void]$sb.AppendLine("`t{")
foreach ($e in $entries) {
  [void]$sb.AppendLine("`t`tmanager.Register(new $($e.Class)(), EL_TestTier.$($e.Tier));")
}
[void]$sb.AppendLine("`t}")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")

$generated = $sb.ToString()

if ($violations.Count -gt 0) {
  Write-Host "gen-test-registry: FAILED ($($violations.Count) violation(s))"
  foreach ($v in $violations) { Write-Host "  - $v" }
  exit 1
}

if ($Write) {
  Set-Content -LiteralPath $generatedPath -Value $generated -NoNewline
  Write-Host "gen-test-registry: OK ($($entries.Count) test class(es) -> $generatedName)"
  exit 0
}

# No flag (e.g. bare run by `cli validate`) means check mode: the generated
# registry must be in sync with the test files.
if ($Check -or -not $Write) {
  if (-not (Test-Path -LiteralPath $generatedPath)) {
    Write-Host "gen-test-registry: FAILED - $generatedName missing (run 'tools\cli regen-tests')"
    exit 1
  }
  $onDisk = Get-Content -LiteralPath $generatedPath -Raw
  if ($onDisk -ne $generated) {
    Write-Host "gen-test-registry: FAILED - $generatedName out of sync with the test files (run 'tools\cli regen-tests')"
    exit 1
  }
  Write-Host "gen-test-registry: OK ($($entries.Count) test class(es) registered, registry in sync)"
  exit 0
}

Write-Host "gen-test-registry: specify -Write or -Check"
exit 2