EL_SirenModes {
 m_Modes {
  EL_SirenMode "{20837DE7519E40D5}" {
   m_NextModeSingleClick "Mode1"
   m_NextModeDoubleClick "Mode2"
   m_Animation EL_LightAnimation "{A2AB27B7168F486C}" {
    m_Entries {
     EL_LightEntry "{609D750054F14766}" {
      m_Type "Turn Off"
     }
    }
   }
   m_SoundWhenPressed "DefaultHorn"
   m_SoundWhenReleased "DefaultHorn"
   m_KnobSignals {
    SignalValuePair "{94A8E30FCCE04F04}" {
     m_Name "Translation"
    }
    SignalValuePair "{4BB4A03ED9F8431B}" {
     m_Name "Rotation"
    }
   }
  }
  EL_SirenMode "{A8A0A91AA3414AD6}" {
   m_Name "Mode1"
   m_NextModeDoubleClick "Mode2"
   m_Animation EL_LightAnimation "{410816090FA84CBE}" {
    m_Entries {
     EL_LightEntry "{1CB0622128444057}" {
      m_DelayMS 200
      m_Type "Turn Off"
     }
     EL_LightEntry "{D1BAE6DC752B4879}" {
      m_DelayMS 200
      m_Name "1"
     }
     EL_LightEntry "{38FBC107C648452E}" {
      m_DelayMS 200
      m_Name "2"
     }
     EL_LightEntry "{1748C1340BF54945}" {
      m_DelayMS 200
      m_Name "3"
     }
     EL_LightEntry "{29EF145FA9244C59}" {
      m_DelayMS 200
      m_Name "4"
     }
     EL_LightEntry "{201A429F3D1F41A6}" {
      m_DelayMS 200
      m_Name "5"
     }
     EL_LightEntry "{2C7F6BA51B0D4E33}" {
      m_DelayMS 200
      m_Type Toggle
     }
     EL_LoopEntry "{647C2A2351834310}" {
      m_StartFrom 1
      m_LoopCount 10
     }
     EL_LoopEntry "{C4B5A647F99448FE}" {
     }
    }
   }
   m_SoundWhenPressed "WarningSiren"
   m_SoundWhenReleased "Silent"
   m_KnobSignals {
    SignalValuePair "{3521E394895B46E5}" {
     m_Name "Translation"
    }
    SignalValuePair "{FF3F1704AE48480F}" {
     m_Name "Rotation"
     m_Value 30
    }
   }
  }
  EL_SirenMode "{9AF508A60D3D45BE}" {
   m_Name "Mode2"
   m_NextModeSingleClick "Mode3"
   m_NextModeDoubleClick "Mode1"
   m_Animation EL_LightAnimation "{D70A01422CF04236}" {
    m_Entries {
     EL_LightEntry "{B44C2EF7DAD94C46}" {
      m_Type "Turn Off"
     }
     EL_LightEntry "{CBB20150C4344D35}" {
      m_DelayMS 100
      m_Name "left1 left3 left5 right2 right4"
     }
     EL_LightEntry "{3197B1382BB44B13}" {
      m_DelayMS 100
      m_Type Toggle
     }
     EL_LoopEntry "{0F162AE6212D4B2B}" {
      m_StartFrom 1
     }
    }
   }
   m_SoundWhenPressed "FastestSiren"
   m_SoundWhenReleased "SlowSiren"
   m_KnobSignals {
    SignalValuePair "{132F23C068D542BB}" {
     m_Name "Translation"
    }
    SignalValuePair "{E7F6176F906F46D1}" {
     m_Name "Rotation"
     m_Value -30
    }
   }
  }
  EL_SirenMode "{34B985E59B7C4A0B}" {
   m_Name "Mode3"
   m_NextModeSingleClick "Mode2"
   m_NextModeDoubleClick "Mode1"
   m_Animation EL_LightAnimation "{DA5FE90ED11F429B}" {
    m_Entries {
     EL_LightEntry "{70E5B90547CF4D2F}" {
     }
     EL_LightEntry "{6708D68486A94B14}" {
      m_DelayMS 100
      m_Type Toggle
     }
     EL_LoopEntry "{5A996818759D45E3}" {
      m_StartFrom 1
     }
    }
   }
   m_SoundWhenPressed "FastestSiren"
   m_SoundWhenReleased "FastSiren"
   m_KnobSignals {
    SignalValuePair "{DF7D0B9EF9B94EBA}" {
     m_Name "Translation"
     m_Value -0.01
    }
   }
  }
 }
}