EL_SirenModes {
 m_Modes {
  EL_SirenMode "{2650D51840444EEA}" {
   m_NextModeSingleClick "Mode1"
   m_NextModeDoubleClick "Mode2"
   m_Animation EL_LightAnimation "{7B97A72E4392492F}" {
    m_Entries {
     EL_LightEntry "{81C36B1F03ED410C}" {
      m_Type "Turn Off"
     }
     EL_AnimationEntry "{33BD7226EE464BA3}" {
      m_Type "Turn Off"
     }
    }
   }
   m_SoundWhenPressed "DefaultHorn"
   m_SoundWhenReleased "DefaultHorn"
   m_KnobSignals {
    SignalValuePair "{34144071A335432A}" {
     m_Name "Translation"
    }
    SignalValuePair "{26FF64B54E504F6F}" {
     m_Name "Rotation"
    }
   }
  }
  EL_SirenMode "{F285CEDF513840FA}" {
   m_Name "Mode1"
   m_NextModeDoubleClick "Mode2"
   m_Animation EL_LightAnimation "{2A4C0CC238BD4A6D}" {
    m_Entries {
     EL_AnimationEntry "{EA94D06B3A214F47}" {
     }
     EL_LightEntry "{DA218CC26B5646B2}" {
     }
    }
   }
   m_SoundWhenPressed "WarningSiren"
   m_SoundWhenReleased "Silent"
   m_KnobSignals {
    SignalValuePair "{C89739088E354BC0}" {
     m_Name "Translation"
    }
    SignalValuePair "{51108CDB56854D28}" {
     m_Name "Rotation"
     m_Value 30
    }
   }
  }
  EL_SirenMode "{157BB5DAC2B648C3}" {
   m_Name "Mode2"
   m_NextModeSingleClick "Mode3"
   m_NextModeDoubleClick "Mode1"
   m_Animation EL_LightAnimation "{15427ABDE67E4F05}" {
    m_Entries {
     EL_LightEntry "{19D12C25139B4CB3}" {
     }
     EL_AnimationEntry "{BEBBDD8F588F4CA1}" {
     }
    }
   }
   m_SoundWhenPressed "FastestSiren"
   m_SoundWhenReleased "SlowSiren"
   m_KnobSignals {
    SignalValuePair "{47A73137D4F44D0F}" {
     m_Name "Translation"
    }
    SignalValuePair "{D06143635C48423F}" {
     m_Name "Rotation"
     m_Value -30
    }
   }
  }
  EL_SirenMode "{33DBAD98575D45B1}" {
   m_Name "Mode3"
   m_NextModeSingleClick "Mode2"
   m_NextModeDoubleClick "Mode1"
   m_Animation EL_LightAnimation "{47729E04FFEE43B1}" {
    m_Entries {
     EL_AnimationEntry "{E79706BB2AAA47C4}" {
     }
     EL_LightEntry "{B267D2F4127C425B}" {
     }
    }
   }
   m_SoundWhenPressed "FastestSiren"
   m_SoundWhenReleased "FastSiren"
   m_KnobSignals {
    SignalValuePair "{153F0387D9E94EA1}" {
     m_Name "Translation"
     m_Value -0.01
    }
   }
  }
 }
}